name = "landing-grid"
description = "A professional, responsive landing grid theme for Zola"
license = "MIT"
min_version = "0.17.0"
homepage = "https://github.com/fastup-one/landing-grid-zola"
demo = "https://yourdemo.com/landing-grid"
keywords = ["landing-page", "dashboard", "grid", "responsive", "modern"]

[author]
name = "Landing Grid Team"
homepage = "https://github.com/fastup-one"

[extra]
screenshot = "screenshot.png"
featured = true